# Generated by Django 4.1.1 on 2024-03-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_nodeconfigbuffer_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='x_length',
            field=models.IntegerField(db_column='x_length'),
        ),
        migrations.AlterField(
            model_name='room',
            name='y_length',
            field=models.IntegerField(db_column='y_length'),
        ),
    ]
