# Generated by Django 4.1.1 on 2024-03-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_room_x_length_alter_room_y_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id', null=True)),
                ('voltage', models.FloatField(db_column='voltage', null=True)),
                ('current', models.FloatField(db_column='current', null=True)),
                ('active_power', models.FloatField(db_column='active_power', null=True)),
                ('power_factor', models.FloatField(db_column='power_factor', null=True)),
                ('frequency', models.FloatField(db_column='frequency', null=True)),
                ('active_energy', models.FloatField(db_column='active_energy', null=True)),
                ('time', models.BigIntegerField(db_column='time')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
    ]
