# Generated by Django 4.1.1 on 2024-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='ip',
            field=models.TextField(db_column='ip', unique=True),
        ),
    ]
